//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaSkillStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetaSkillStudio.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Analytics.
        /// </summary>
        public static string Action_Analytics {
            get {
                return ResourceManager.GetString("Action_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create _Benchmarks.
        /// </summary>
        public static string Action_CreateBenchmarks {
            get {
                return ResourceManager.GetString("Action_CreateBenchmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Create Skill.
        /// </summary>
        public static string Action_CreateSkill {
            get {
                return ResourceManager.GetString("Action_CreateSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Improve Skill.
        /// </summary>
        public static string Action_ImproveSkill {
            get {
                return ResourceManager.GetString("Action_ImproveSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Meta Manage.
        /// </summary>
        public static string Action_MetaManage {
            get {
                return ResourceManager.GetString("Action_MetaManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh R_uns.
        /// </summary>
        public static string Action_RefreshRuns {
            get {
                return ResourceManager.GetString("Action_RefreshRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refresh Skills.
        /// </summary>
        public static string Action_RefreshSkills {
            get {
                return ResourceManager.GetString("Action_RefreshSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string Action_Settings {
            get {
                return ResourceManager.GetString("Action_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Test / Benchmark.
        /// </summary>
        public static string Action_TestBenchmark {
            get {
                return ResourceManager.GetString("Action_TestBenchmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - AI Skill Management.
        /// </summary>
        public static string App_Subtitle {
            get {
                return ResourceManager.GetString("App_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions Section.
        /// </summary>
        public static string Automation_ActionsSection {
            get {
                return ResourceManager.GetString("Automation_ActionsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Title Meta Skill Studio.
        /// </summary>
        public static string Automation_AppTitle {
            get {
                return ResourceManager.GetString("Automation_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty State: No runs recorded yet.
        /// </summary>
        public static string Automation_EmptyState {
            get {
                return ResourceManager.GetString("Automation_EmptyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Section.
        /// </summary>
        public static string Automation_OutputSection {
            get {
                return ResourceManager.GetString("Automation_OutputSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Text.
        /// </summary>
        public static string Automation_OutputText {
            get {
                return ResourceManager.GetString("Automation_OutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Indicator.
        /// </summary>
        public static string Automation_ProgressIndicator {
            get {
                return ResourceManager.GetString("Automation_ProgressIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run History List.
        /// </summary>
        public static string Automation_RunHistoryList {
            get {
                return ResourceManager.GetString("Automation_RunHistoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run History Section.
        /// </summary>
        public static string Automation_RunHistorySection {
            get {
                return ResourceManager.GetString("Automation_RunHistorySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Status.
        /// </summary>
        public static string Automation_RuntimeStatus {
            get {
                return ResourceManager.GetString("Automation_RuntimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Count.
        /// </summary>
        public static string Automation_SkillCount {
            get {
                return ResourceManager.GetString("Automation_SkillCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Message.
        /// </summary>
        public static string Automation_StatusMessage {
            get {
                return ResourceManager.GetString("Automation_StatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string Button_CopyClipboard {
            get {
                return ResourceManager.GetString("Button_CopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Runtimes.
        /// </summary>
        public static string Button_DetectRuntimes {
            get {
                return ResourceManager.GetString("Button_DetectRuntimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Pipeline.
        /// </summary>
        public static string Button_StartPipeline {
            get {
                return ResourceManager.GetString("Button_StartPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Activity (Last 30 Days).
        /// </summary>
        public static string Chart_RunActivity {
            get {
                return ResourceManager.GetString("Chart_RunActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Quality Score by Skill.
        /// </summary>
        public static string Chart_QualityScoreBySkill {
            get {
                return ResourceManager.GetString("Chart_QualityScoreBySkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Rate by Skill.
        /// </summary>
        public static string Chart_PassRateBySkill {
            get {
                return ResourceManager.GetString("Chart_PassRateBySkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark cases include trigger-positive, trigger-negative, and behavior validation scenarios.
        /// </summary>
        public static string Desc_BenchmarkCases {
            get {
                return ResourceManager.GetString("Desc_BenchmarkCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate evaluation test cases for a skill.
        /// </summary>
        public static string Desc_CreateBenchmarks {
            get {
                return ResourceManager.GetString("Desc_CreateBenchmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a brief description of the skill you want to create.
        /// </summary>
        public static string Desc_CreateSkill {
            get {
                return ResourceManager.GetString("Desc_CreateSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute multi-phase skill pipelines with state persistence.
        /// </summary>
        public static string Desc_Pipeline {
            get {
                return ResourceManager.GetString("Desc_Pipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure AI runtimes and models for each operational role.
        /// </summary>
        public static string Desc_RuntimeConfig {
            get {
                return ResourceManager.GetString("Desc_RuntimeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill health, trends, and performance metrics.
        /// </summary>
        public static string Desc_Analytics {
            get {
                return ResourceManager.GetString("Desc_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a skill from the list below.
        /// </summary>
        public static string Desc_SelectSkill {
            get {
                return ResourceManager.GetString("Desc_SelectSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifacts.
        /// </summary>
        public static string Expander_Artifacts {
            get {
                return ResourceManager.GetString("Expander_Artifacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Parameters.
        /// </summary>
        public static string Expander_InputParameters {
            get {
                return ResourceManager.GetString("Expander_InputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Expander_Metadata {
            get {
                return ResourceManager.GetString("Expander_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Error.
        /// </summary>
        public static string Expander_Stderr {
            get {
                return ResourceManager.GetString("Expander_Stderr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Output.
        /// </summary>
        public static string Expander_Stdout {
            get {
                return ResourceManager.GetString("Expander_Stdout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Grid_Quality {
            get {
                return ResourceManager.GetString("Grid_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Run.
        /// </summary>
        public static string Grid_LastRun {
            get {
                return ResourceManager.GetString("Grid_LastRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass Rate.
        /// </summary>
        public static string Grid_PassRate {
            get {
                return ResourceManager.GetString("Grid_PassRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string Grid_Skill {
            get {
                return ResourceManager.GetString("Grid_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Runs.
        /// </summary>
        public static string Grid_TotalRuns {
            get {
                return ResourceManager.GetString("Grid_TotalRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend.
        /// </summary>
        public static string Grid_Trend {
            get {
                return ResourceManager.GetString("Grid_Trend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Header_Alerts {
            get {
                return ResourceManager.GetString("Header_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Benchmark Cases.
        /// </summary>
        public static string Header_CreateBenchmarkCases {
            get {
                return ResourceManager.GetString("Header_CreateBenchmarkCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Skill.
        /// </summary>
        public static string Header_CreateNewSkill {
            get {
                return ResourceManager.GetString("Header_CreateNewSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Header_Output {
            get {
                return ResourceManager.GetString("Header_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline Progress.
        /// </summary>
        public static string Header_PipelineProgress {
            get {
                return ResourceManager.GetString("Header_PipelineProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Configuration.
        /// </summary>
        public static string Header_RuntimeConfiguration {
            get {
                return ResourceManager.GetString("Header_RuntimeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run History.
        /// </summary>
        public static string Header_RunHistory {
            get {
                return ResourceManager.GetString("Header_RunHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Header_Actions {
            get {
                return ResourceManager.GetString("Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Health Overview.
        /// </summary>
        public static string Header_SkillHealthOverview {
            get {
                return ResourceManager.GetString("Header_SkillHealthOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark Goal:.
        /// </summary>
        public static string Label_BenchmarkGoal {
            get {
                return ResourceManager.GetString("Label_BenchmarkGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief/Goal:.
        /// </summary>
        public static string Label_BriefGoal {
            get {
                return ResourceManager.GetString("Label_BriefGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Count:.
        /// </summary>
        public static string Label_CaseCount {
            get {
                return ResourceManager.GetString("Label_CaseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string Label_Duration {
            get {
                return ResourceManager.GetString("Label_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended:.
        /// </summary>
        public static string Label_Ended {
            get {
                return ResourceManager.GetString("Label_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Code:.
        /// </summary>
        public static string Label_ExitCode {
            get {
                return ResourceManager.GetString("Label_ExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        public static string Label_Model {
            get {
                return ResourceManager.GetString("Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline Type:.
        /// </summary>
        public static string Label_PipelineType {
            get {
                return ResourceManager.GetString("Label_PipelineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Fixes:.
        /// </summary>
        public static string Label_PriorityFixes {
            get {
                return ResourceManager.GetString("Label_PriorityFixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Score.
        /// </summary>
        public static string Label_QualityScore {
            get {
                return ResourceManager.GetString("Label_QualityScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Notes:.
        /// </summary>
        public static string Label_RoutingNotes {
            get {
                return ResourceManager.GetString("Label_RoutingNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime:.
        /// </summary>
        public static string Label_Runtime {
            get {
                return ResourceManager.GetString("Label_Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Brief:.
        /// </summary>
        public static string Label_SkillBrief {
            get {
                return ResourceManager.GetString("Label_SkillBrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Name:.
        /// </summary>
        public static string Label_SkillName {
            get {
                return ResourceManager.GetString("Label_SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started:.
        /// </summary>
        public static string Label_Started {
            get {
                return ResourceManager.GetString("Label_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Library:.
        /// </summary>
        public static string Label_TargetLibrary {
            get {
                return ResourceManager.GetString("Label_TargetLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Skill:.
        /// </summary>
        public static string Label_TargetSkill {
            get {
                return ResourceManager.GetString("Label_TargetSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibraryUnverified (default).
        /// </summary>
        public static string Library_Unverified {
            get {
                return ResourceManager.GetString("Library_Unverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw, untested skills go here before workbench promotion.
        /// </summary>
        public static string Library_Unverified_Description {
            get {
                return ResourceManager.GetString("Library_Unverified_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibraryWorkbench.
        /// </summary>
        public static string Library_Workbench {
            get {
                return ResourceManager.GetString("Library_Workbench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills under active development and testing.
        /// </summary>
        public static string Library_Workbench_Description {
            get {
                return ResourceManager.GetString("Library_Workbench_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating benchmarks....
        /// </summary>
        public static string Op_CreatingBenchmarks {
            get {
                return ResourceManager.GetString("Op_CreatingBenchmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating skill....
        /// </summary>
        public static string Op_CreatingSkill {
            get {
                return ResourceManager.GetString("Op_CreatingSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improving skill....
        /// </summary>
        public static string Op_ImprovingSkill {
            get {
                return ResourceManager.GetString("Op_ImprovingSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading skills....
        /// </summary>
        public static string Op_LoadingSkills {
            get {
                return ResourceManager.GetString("Op_LoadingSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing meta-library....
        /// </summary>
        public static string Op_MetaManaging {
            get {
                return ResourceManager.GetString("Op_MetaManaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing runs....
        /// </summary>
        public static string Op_RefreshingRuns {
            get {
                return ResourceManager.GetString("Op_RefreshingRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running tests....
        /// </summary>
        public static string Op_RunningTests {
            get {
                return ResourceManager.GetString("Op_RunningTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration updated successfully..
        /// </summary>
        public static string Output_ConfigurationUpdated {
            get {
                return ResourceManager.GetString("Output_ConfigurationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating skill in {0}....
        /// </summary>
        public static string Output_CreatingInLibrary {
            get {
                return ResourceManager.GetString("Output_CreatingInLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit code: {0}.
        /// </summary>
        public static string Output_ExitCode {
            get {
                return ResourceManager.GetString("Output_ExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} skills from repository..
        /// </summary>
        public static string Output_LoadedSkillsCount {
            get {
                return ResourceManager.GetString("Output_LoadedSkillsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} runs..
        /// </summary>
        public static string Output_LoadedRunsCount {
            get {
                return ResourceManager.GetString("Output_LoadedRunsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No runs directory found..
        /// </summary>
        public static string Output_NoRunsDirectory {
            get {
                return ResourceManager.GetString("Output_NoRunsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was cancelled..
        /// </summary>
        public static string Output_OperationCancelled {
            get {
                return ResourceManager.GetString("Output_OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Score: {0}.
        /// </summary>
        public static string Output_QualityScore {
            get {
                return ResourceManager.GetString("Output_QualityScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing all skills....
        /// </summary>
        public static string Output_TestingAllSkills {
            get {
                return ResourceManager.GetString("Output_TestingAllSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing skill: {0}.
        /// </summary>
        public static string Output_TestingSkill {
            get {
                return ResourceManager.GetString("Output_TestingSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Meta Skill Studio. Ready to manage your AI skills. Configure runtimes via Settings button before first use.
        /// </summary>
        public static string Output_Welcome {
            get {
                return ResourceManager.GetString("Output_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Pipeline.
        /// </summary>
        public static string Pipeline_Creation {
            get {
                return ResourceManager.GetString("Pipeline_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvement Pipeline.
        /// </summary>
        public static string Pipeline_Improvement {
            get {
                return ResourceManager.GetString("Pipeline_Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Management Pipeline.
        /// </summary>
        public static string Pipeline_LibraryManagement {
            get {
                return ResourceManager.GetString("Pipeline_LibraryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This runtime will be used for creating new skills from scratch..
        /// </summary>
        public static string Role_Create_Description {
            get {
                return ResourceManager.GetString("Role_Create_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Skills.
        /// </summary>
        public static string Role_Create_Title {
            get {
                return ResourceManager.GetString("Role_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This runtime will be used as the judge for quality evaluation of skill outputs..
        /// </summary>
        public static string Role_Judge_Description {
            get {
                return ResourceManager.GetString("Role_Judge_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLM Judge.
        /// </summary>
        public static string Role_Judge_Title {
            get {
                return ResourceManager.GetString("Role_Judge_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This runtime will be used for meta-library management, catalog curation, and lifecycle operations..
        /// </summary>
        public static string Role_Orchestrate_Description {
            get {
                return ResourceManager.GetString("Role_Orchestrate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Management.
        /// </summary>
        public static string Role_Orchestrate_Title {
            get {
                return ResourceManager.GetString("Role_Orchestrate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This runtime will be used for improving existing skills based on anti-pattern scans or specific goals..
        /// </summary>
        public static string Role_Improve_Description {
            get {
                return ResourceManager.GetString("Role_Improve_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improving Skills.
        /// </summary>
        public static string Role_Improve_Title {
            get {
                return ResourceManager.GetString("Role_Improve_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This runtime will be used for running evaluations, benchmarks, and trigger tests..
        /// </summary>
        public static string Role_Test_Description {
            get {
                return ResourceManager.GetString("Role_Test_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing / Benchmarking / Evaluating.
        /// </summary>
        public static string Role_Test_Title {
            get {
                return ResourceManager.GetString("Role_Test_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent Quality.
        /// </summary>
        public static string Score_Excellent {
            get {
                return ResourceManager.GetString("Score_Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Quality.
        /// </summary>
        public static string Score_Good {
            get {
                return ResourceManager.GetString("Score_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptable Quality.
        /// </summary>
        public static string Score_Acceptable {
            get {
                return ResourceManager.GetString("Score_Acceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Improvement.
        /// </summary>
        public static string Score_NeedsImprovement {
            get {
                return ResourceManager.GetString("Score_NeedsImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor Quality.
        /// </summary>
        public static string Score_Poor {
            get {
                return ResourceManager.GetString("Score_Poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} runtime(s) available.
        /// </summary>
        public static string Skills_CountFormat {
            get {
                return ResourceManager.GetString("Skills_CountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Tab_Create {
            get {
                return ResourceManager.GetString("Tab_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve.
        /// </summary>
        public static string Tab_Improve {
            get {
                return ResourceManager.GetString("Tab_Improve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge.
        /// </summary>
        public static string Tab_Judge {
            get {
                return ResourceManager.GetString("Tab_Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orchestrate.
        /// </summary>
        public static string Tab_Orchestrate {
            get {
                return ResourceManager.GetString("Tab_Orchestrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Tab_Overview {
            get {
                return ResourceManager.GetString("Tab_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Tab_Test {
            get {
                return ResourceManager.GetString("Tab_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string Tab_Trends {
            get {
                return ResourceManager.GetString("Tab_Trends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED.
        /// </summary>
        public static string Status_Failed {
            get {
                return ResourceManager.GetString("Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        public static string Status_Success {
            get {
                return ResourceManager.GetString("Status_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string Status_Busy {
            get {
                return ResourceManager.GetString("Status_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting runtimes....
        /// </summary>
        public static string Status_DetectingRuntimes {
            get {
                return ResourceManager.GetString("Status_DetectingRuntimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading analytics....
        /// </summary>
        public static string Status_LoadingAnalytics {
            get {
                return ResourceManager.GetString("Status_LoadingAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No runs recorded yet.
        /// </summary>
        public static string Status_NoRunsYet {
            get {
                return ResourceManager.GetString("Status_NoRunsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start pipeline.
        /// </summary>
        public static string Status_ReadyToStartPipeline {
            get {
                return ResourceManager.GetString("Status_ReadyToStartPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime detection failed.
        /// </summary>
        public static string Status_RuntimeDetectionFailed {
            get {
                return ResourceManager.GetString("Status_RuntimeDetectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} runtime(s) available.
        /// </summary>
        public static string Status_RuntimesAvailable {
            get {
                return ResourceManager.GetString("Status_RuntimesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new skill in LibraryUnverified or LibraryWorkbench (Alt+C).
        /// </summary>
        public static string Tooltip_CreateSkill {
            get {
                return ResourceManager.GetString("Tooltip_CreateSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate benchmark test cases for a skill (Alt+B).
        /// </summary>
        public static string Tooltip_CreateBenchmarks {
            get {
                return ResourceManager.GetString("Tooltip_CreateBenchmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve an existing skill with a specific goal (Alt+I).
        /// </summary>
        public static string Tooltip_ImproveSkill {
            get {
                return ResourceManager.GetString("Tooltip_ImproveSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute meta-library management operations (Alt+M).
        /// </summary>
        public static string Tooltip_MetaManage {
            get {
                return ResourceManager.GetString("Tooltip_MetaManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View skill health analytics and trends (Alt+A).
        /// </summary>
        public static string Tooltip_Analytics {
            get {
                return ResourceManager.GetString("Tooltip_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh run history (Alt+U).
        /// </summary>
        public static string Tooltip_RefreshRuns {
            get {
                return ResourceManager.GetString("Tooltip_RefreshRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload skill list from repository (Alt+R).
        /// </summary>
        public static string Tooltip_RefreshSkills {
            get {
                return ResourceManager.GetString("Tooltip_RefreshSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure runtimes and models (Alt+S).
        /// </summary>
        public static string Tooltip_Settings {
            get {
                return ResourceManager.GetString("Tooltip_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run validation, evaluation, and judge on a skill or all skills (Alt+T).
        /// </summary>
        public static string Tooltip_TestBenchmark {
            get {
                return ResourceManager.GetString("Tooltip_TestBenchmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics Dashboard.
        /// </summary>
        public static string WindowTitle_Analytics {
            get {
                return ResourceManager.GetString("WindowTitle_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Benchmarks.
        /// </summary>
        public static string WindowTitle_Benchmark {
            get {
                return ResourceManager.GetString("WindowTitle_Benchmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Skill.
        /// </summary>
        public static string WindowTitle_CreateSkill {
            get {
                return ResourceManager.GetString("WindowTitle_CreateSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Skill Studio.
        /// </summary>
        public static string WindowTitle_Main {
            get {
                return ResourceManager.GetString("WindowTitle_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline Execution.
        /// </summary>
        public static string WindowTitle_Pipeline {
            get {
                return ResourceManager.GetString("WindowTitle_Pipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Details.
        /// </summary>
        public static string WindowTitle_RunDetails {
            get {
                return ResourceManager.GetString("WindowTitle_RunDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings - Runtime Configuration.
        /// </summary>
        public static string WindowTitle_Settings {
            get {
                return ResourceManager.GetString("WindowTitle_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Skill.
        /// </summary>
        public static string WindowTitle_SelectSkill {
            get {
                return ResourceManager.GetString("WindowTitle_SelectSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New skill (no target).
        /// </summary>
        public static string Checkbox_NewSkill {
            get {
                return ResourceManager.GetString("Checkbox_NewSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test all skills (no selection required).
        /// </summary>
        public static string Checkbox_TestAllSkills {
            get {
                return ResourceManager.GetString("Checkbox_TestAllSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMAND ERROR: {0}.
        /// </summary>
        public static string Error_CommandExecution {
            get {
                return ResourceManager.GetString("Error_CommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No skills available. Please check repository connection..
        /// </summary>
        public static string Error_NoSkillsAvailable {
            get {
                return ResourceManager.GetString("Error_NoSkillsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Skills.
        /// </summary>
        public static string Error_Title_NoSkills {
            get {
                return ResourceManager.GetString("Error_Title_NoSkills", resourceCulture);
            }
        }
    }
}
